server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'naman'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'